apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: monitoring
    name: prometheus-alertmanager
  hostPath:
    path: "/data/prometheus-alertmanager/"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: monitoring
    name: prometheus-server
  hostPath:
    path: "/data/prometheus-server/"
