apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci
rules:
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  verbs: ["*"]
