kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ci-binding
  namespace: default
subjects:
- kind: User
  name: ci
  apiGroup: ""
roleRef:
  kind: Role
  name: dev
  apiGroup: ""

